### ISSUE TITLE
Tire 用中文字符的存储效率？

### ISSUE THREAD

**Issue by RominYue** [wklken/suggestion#7]
看了suggestion的py实现，受益匪浅。但是有点疑惑：
1. 中文字符大概8万，常用字大概3500，假设节点只用常用字的话，假设query的长度最长是10的话，给定一个节点，它的子节点数量有可能是3500，最坏情况下，这颗Tire树总共有 (3500)^10个节点，，这太耗费内存了吧
2. 自己想到用拼音，不知道楼主这边支持不，拼音的字符加上音调，总共加起来也不超过40个字符，但是拼音的问题是有多对一的映射关系。比如 “稀饭”，“西范“ 对应同一个拼音加音调。。 还有个问题就是性能的问题了，查找路径比中文字符的要长。

想听听楼主的想法 
PS： darts指的是 double array Trie 么，这个如何实现suggestion

**Comment by wklken** [comment]
1. 在前前公司, 使用py版本的, 30W 词(原词/拼音/拼音首字母, 总的接近90W 了), 每天几百万请求, 毫无压力(当然,用了redis), 当时内存大概2G不到. 
2. 在前公司, 用的是最终版的double array trie, 就是darts这个库, 只是把原来树状的结构变成了双数组存储和索引, 性能和内存占用优化都提升很大.

二者都有在生产环境中使用, 只是double array trie的话, 可读性和扩展性较低, 例如拼音/首字母等, 也都还没实现(计划中)

**Comment by wklken** [comment]
拼音的话, 当时应该是引入了额外的map
例如

```
xifan - [稀饭, 洗翻]   
id - xifan
```

然后在树节点中放的是id, 这样命中后, 反向通过id拿到词组, 再做处理

首字母同上

**Comment by RominYue** [comment]
谢谢！还有个疑问，redis缓存存的还是搜索次数多的suggestions，trie树还是建在内存里呗（trie和redis没关系？）

**Comment by wklken** [comment]
trie和redis没关系, 在词进来时, 先到redis查下有的话直接返回, 减少搜索trie, 因为这个操作是cpu密集型的
